### ISSUE TITLE
Is there a way to control the permission of the vendor-prefixed folder?

### ISSUE THREAD

**Issue by estevao90** [BrianHenryIE/strauss#104]
Starting in `v0.16.0`, the permission of the `vendor-prefixed` folder was changed to `0600`. I think it's related to [this commit](https://github.com/BrianHenryIE/strauss/commit/014faac79d7e2e896f24ded10eebf277c538765a), and it's not intentional. 

Is there any chance to use (0755) as default again? Or maybe introduce a parameter to allow us to change the permission?

The default value for the `vendor` folder is `0775`. `0600` is very restrictive and may cause issues in servers managed by groups.

Thank you.

**Comment by BrianHenryIE** [comment]
Fixed in master https://github.com/BrianHenryIE/strauss/commit/c9fa47e48196a044b55b69b978c5cf653628f271

**Comment by BrianHenryIE** [comment]
That is released now in [0.19.2](https://github.com/BrianHenryIE/strauss/releases/tag/0.19.2). Thanks.

**Comment by estevao90** [comment]
@BrianHenryIE , I just figured out another related issue. 

The subfolders in `vendor-prefixed ` do not have the correct permissions. 

Looking at the code, we need to set visibility for the copied folders in this part https://github.com/BrianHenryIE/strauss/blob/master/src/Copier.php#L84

**Comment by estevao90** [comment]
@BrianHenryIE , any update on it? Thanks!
