### ISSUE TITLE
PHP Fatal error:  Trait "Psr\Log\LoggerAwareTrait" not found in C:\********\vendor\brianhenryie\strauss\src\Console\Commands\Compose.php on line 28

### ISSUE THREAD

**Issue by mbucher100** [BrianHenryIE/strauss#107]
Composer require leads to a PHP fatal error in Compose.php.

![image](https://github.com/BrianHenryIE/strauss/assets/58312460/21dc0b0a-4e85-4cb8-b2de-f14d07a47d58)

[composer.json](https://github.com/BrianHenryIE/strauss/files/15372771/composer.json)

**Comment by BrianHenryIE** [comment]
It is working as expected. You're using `"delete_vendor_packages": true`. It runs without an error. Then on the second run, that package is no longer available for your dev dependencies. See issue #81 for discussion.

**Comment by BrianHenryIE** [comment]
See #162
