### ISSUE TITLE
Missing namespace prefixes since migrating from "coenjacobs/mozart": "dev-rewrite" and url in composer

### ISSUE THREAD

**Issue by MikeiLL** [BrianHenryIE/strauss#11]
Hi, Brian.

I migrated my composer file from 

```
"repositories": [
    {
      "url": "https://github.com/brianhenryie/mozart",
      "type": "git"
    },
  ],
  "require-dev":{
    "coenjacobs/mozart": "dev-rewrite",
    "squizlabs/php_codesniffer": "*",
     "wp-coding-standards/wpcs": "*"
  },
```

to

```

```

With config:

```

    "strauss": {
      "dep_namespace": "MZoo\\MBO_Sandbox\\Dependencies\\",
      "dep_directory": "/src/Mozart/",
      "packages": [
        "htmlburger/carbon-fields",
        "ericmann/wp-session-manager",
        "ericmann/sessionz"
      ],
      "delete_vendor_files": false,
      "override_autoload": {
        "htmlburger/carbon-fields": {
          "psr-4": {
            "Carbon_Fields\\": "core/"
          },
          "files": [
            "config.php",
            "templates",
            "assets",
            "build"
          ]
        }
      }
    }
  }
```

I'm not quite sure how you are achieving the namespace prefixes, but it seems ones within Carbon Fields are breaking.

It breaks:

```
Uncaught Error: Class 'Carbon_Fields\Provider\Container_Condition_Provider' not found in path/to/src/Mozart/htmlburger/carbon-fields/core/Carbon_Fields.php:392
```

Then when I update that namespace to:
```
\MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Provider\Container_Condition_Provider
```

It breaks at:
```
Uncaught Error: Class 'Carbon_Fields\Carbon_Fields' not found in path/to/src/Mozart/htmlburger/carbon-fields/core/Loader/Loader.php:6
```

I have of course removed `vendor` and re-installed with re-running `vendor/bin/strauss` (Cool name, BTW.)
Am I missing a configuration or a step?

Diffs I see in the rendered files are, significantly:
```
# src/Mozart/htmlburger/carbon-fields/core/Carbon_Fields.php

```
And
-		$ioc->register( new \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Provider\Container_Condition_Provider() );
+		$ioc->register( new \Carbon_Fields\Provider\Container_Condition_Provider() );
```
# src/Mozart/htmlburger/carbon-fields/core/Container.php
  * Container proxy factory class.
  * Used for shorter namespace access when creating a container.
  *
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Comment_Meta_Container make_comment_meta( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Nav_Menu_Item_Container make_nav_menu_item( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Network_Container make_network( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Post_Meta_Container make_post_meta( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Term_Meta_Container make_term_meta( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\Theme_Options_Container make_theme_options( string $id, string $name = null )
- * @method static \MZoo\MBO_Sandbox\Dependencies\Carbon_Fields\Container\User_Meta_Container make_user_meta( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Comment_Meta_Container make_comment_meta( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Nav_Menu_Item_Container make_nav_menu_item( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Network_Container make_network( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Post_Meta_Container make_post_meta( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Term_Meta_Container make_term_meta( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\Theme_Options_Container make_theme_options( string $id, string $name = null )
+ * @method static \Carbon_Fields\Container\User_Meta_Container make_user_meta( string $id, string $name = null )
```

Thank you and if this is a bug, please feel free to let me know how I can help.

**Comment by BrianHenryIE** [comment]
I've got [the repo on Packagist now](https://packagist.org/packages/brianhenryie/strauss) so all you need is 

```
"require-dev":{
  "brianhenryie/strauss":"*"
}
```

And whatever config you need.

I did notice you mixing `strauss` config keyword with terminology from `mozart` so I changed things so both should work interchangeably. 

And I fixed the un-prefixed `new \Namespaced\Class()` and `static`. The [code for replacing](https://github.com/BrianHenryIE/strauss/blob/81603a3a513fe8fef0315c805dd39b9e3511ea4d/src/Prefixer.php#L125-L154) could probably be made a lot more generic. Every [extra test](https://github.com/BrianHenryIE/strauss/blob/f8938bb52909d4034e642a8fe11b9f274789bcc1/tests/Unit/PrefixerTest.php#L688-L726) will make that a little easier to do.

Thanks.

**Comment by MikeiLL** [comment]
Wanted up update this, and am curious if you have any insight.

As you can see in this [CF issue](https://github.com/htmlburger/carbon-fields/issues/1005#issuecomment-836959588), Carbon Fields is designed to stay in its own `__NAMESPACE__`. It's `boot()` method checks to see if it's already been defined (within another theme or plugin), so when I was using it in two different plugins, in different namespaces, it was booting twice.

So for the moment, I have removed it from Strauss and am keeping it in its original namespace and in vendor.

It would be cool to move it to the Strauss/Mozart directory and keep it in the same namespace, though... I think.

Any sage advice?

**Comment by BrianHenryIE** [comment]
Add:

```
"exclude_from_prefix": {
  "packages": [
    "htmlburger/carbon-fields"
  ]
}
```

and it will continue to copy the files, but won't prefix their namespaces.

If the package had dependencies (this one does not), those would be prefixed and references to the updated classnames and prefixes would be updated inside the excluded package.

I think that's what you're looking for.

You might want to take a look at [Jetpack autoloader](https://github.com/Automattic/jetpack-autoloader) which only loads the latest version of a package..
