### ISSUE TITLE
Current project namespaces not included in vendor-prefixed autoloading

### ISSUE THREAD

**Issue by nathanbrnrd** [BrianHenryIE/strauss#113]
Hi there,

Thanks a lot for your package.
It helped me a lot while other packages did not work on my WP plugin.
I use Strauss because I have several plugin using Google Cloud Client libraries and a conflit happened on some of there dependencies (google/cloud-core).

Your plugin works great :)

The only thing is that my project namespaces are not autoloading unless I still require the old vendor/autoload.php.
I use the default config with vendor-prefixed/ but it only loads the required packages.

So I end up with 2 autoloads in order for the plugin to work.
```
require 'vendor/autoload.php';
require 'vendor-prefixed/autoload.php';
```

The `vendor/autoload.php` is still necessary to load this part of my composer.json:
```
    "autoload": {
        "psr-4": {
            "AEWP_ETC\\Inc\\": "Inc/",
            "AEWP_ETC\\Admin\\": "Admin/"
        }
    },
```
And it still contains the original autloading with the original dependencies.

I am missing something here?

Thanks a lot :)

**Comment by BrianHenryIE** [comment]
Try:

```
    "autoload": {
        "psr-4": {
            "AEWP_ETC\\Inc\\": "Inc/",
            "AEWP_ETC\\Admin\\": "Admin/"
        },
        "classmap": "vendor-prefixed"
    },
```

Then you might want a `vendor-prefixed/.gitignore` file:

```
*
!.gitignore
```

otherwise when you pull your project fresh, Composer will fail because the directory it has been asked to scan for classes does not exist.

Another option is to try setting the Strauss config `target_directory` to `vendor` and it will make the changes to the original files. This can affect your dev-dependencies but eventually should be seamless (there's an open issue for it).

**Comment by nathanbrnrd** [comment]
Thanks @BrianHenryIE 
Will give a try to the first solution.

For now I prefer to keep the vendor directory intact as this allows me to test locally for some packages.
Just adding the namespace for google/cloud-pubsub and its dependencies takes 7 min.
So I do not want to run Strauss every time I want to test another package.

Will keep you posted !

**Comment by BrianHenryIE** [comment]
I don't know if it applies to `google/cloud-pubsub` but Google's PHP SDK has a tool for thinning itself out.

It works in `composer.json` like:

```json
  "extra": {
    "google/apiclient-services": [
      "Gmail"
    ]
  },
  "scripts": {
    "pre-autoload-dump": [
      "Google\\Task\\Composer::cleanup"
    ]
  }
```


https://github.com/googleapis/google-api-php-client?tab=readme-ov-file#cleaning-up-unused-services

https://github.com/googleapis/google-api-php-client/blob/b1f63d72c44307ec8ef7bf18f1012de35d8944ed/src/Task/Composer.php#L31
