### ISSUE TITLE
Strings are being namespaced

### ISSUE THREAD

**Issue by zackkatz** [BrianHenryIE/strauss#15]
The namespace being updated is `TrustedLogin`, a word which is also used in strings. After running Strauss, the strings get modified:

- Before: `esc_html__( 'Learn about TrustedLogin', 'trustedlogin' )`
- After: `esc_html__( 'Learn about GravityView\TrustedLogin', 'trustedlogin' )`

**Comment by BrianHenryIE** [comment]
That should be fixed for you now.

Replacing inside strings is sometimes valid. It was https://github.com/coenjacobs/mozart/issues/13 I was trying to fix when I introduced this behaviour. For now I've just added a check for any spaces before the namespace name.
