### ISSUE TITLE
Windows: File already exists at path

### ISSUE THREAD

**Issue by Spreeuw** [BrianHenryIE/strauss#18]
This seems to be a regression, which I believe was fixed in Mozart by either https://github.com/coenjacobs/mozart/pull/91 or https://github.com/coenjacobs/mozart/pull/103

on Windows, the directory separator is not cleaned for the `files` to be copied in the enumerator here:
https://github.com/BrianHenryIE/strauss/blob/836d1960d551e09885b8f164f61f19cc3562baec/src/FileEnumerator.php#L119

adding this below that line fixes the issue:
https://github.com/BrianHenryIE/strauss/blob/836d1960d551e09885b8f164f61f19cc3562baec/src/FileEnumerator.php#L148

to replicate, simply use:
```
    "require": {
        "iio/libmergepdf": "^4.0"
   },
```

**Comment by BrianHenryIE** [comment]
Thanks. I moved to an M1 MacBook so don't have my Windows VM anymore. I also didn't write any new tests for this. But it's probably fine!

**Comment by Spreeuw** [comment]
Thanks! Github Actions does seem to have windows available too, so that could perhaps be an alternative to running a VM locally?

**Comment by BrianHenryIE** [comment]
Yeah. I only got PHP 8 running on GitHub Actions yesterday, so... eventually!

Good news for you: I've been working with Mpdf and Fpdf a lot lately, so hopefully most issues related to them I suffered through and fixed and they won't bother you.
