### ISSUE TITLE
docblock comment "class object" resulting in prefixed "object"

### ISSUE THREAD

**Issue by Spreeuw** [BrianHenryIE/strauss#19]
using just this:
```
    "require": {
        "iio/libmergepdf": "^4.0"
   },
```
results in `object` being prefixed in all files. This appears to be caused by the following docblock (in: [tecnickcom/tcpdf/include/tcpdf_static.php#L326-L332](https://github.com/tecnickcom/TCPDF/blob/cf8a66c8ec6911bb04f45ccbbf56f2992e6e2139/include/tcpdf_static.php#L326-L332))
```php
	/**
	 * Creates a copy of a class object
	 * @param $object (object) class object to be cloned
	 * @return cloned object
	 * @since 4.5.029 (2009-03-19)
	 * @public static
	 */
```

If I change that first line to `Creates a copy of a classy object`, the issue is resolved

**Comment by BrianHenryIE** [comment]
Looks like the regex to skip multiline comments when searching for class names wasn't working. And it also showed another bug where variables matching a discovered class name were being prefixed inside the variable name itself! Maybe all reserved PHP keywords should be excluded too.
