### ISSUE TITLE
Clean up merged branches

### ISSUE THREAD

**Issue by szepeviktor** [BrianHenryIE/strauss#2]
Hello!

Could you clean up these +0 branches?
https://github.com/BrianHenryIE/strauss/branches

---

I'm planning to send at least 1 PR :)

**Comment by BrianHenryIE** [comment]
I've deleted the +0 branches. 

I didn't realise this would happen, but that closed the PRs to Mozart that were related to those branches. Thankfully the diffs were preserved in the now-closed PRs. The PRs are still valid solutions to Mozart's issues.

I'll close more soon.

**Comment by szepeviktor** [comment]
They were almost 🎂 1 year old.

**Comment by BrianHenryIE** [comment]
I've deleted all the branches now.

Leaving just master and [gh-pages](https://brianhenryie.github.io/strauss/).

Thanks for the encouragement.
