### ISSUE TITLE
Trips up when presented with non-standard packages

### ISSUE THREAD

**Issue by Flickwire** [BrianHenryIE/strauss#22]
As metapackages do not follow the standard directory structure, Strauss has trouble dealing with them, as it cannot find their composer.json. An example of this can be seen by requiring league/omnipay. A workaround for this is to require the packages from the metapackage separately, but it would be more elegant if Strauss could handle this gracefully.

This also applies to other non-standard package types. For instance, if requiring composer/installers such that we can declare our package as a wordpress-plugin, rather than a library, strauss is unable to locate the package 'composer-plugin-api' and fails to compose dependencies.

I am unsure the best way to deal with these special cases - Perhaps at least in the case of composer-plugin-api we simply exclude this package by default

**Comment by Flickwire** [comment]
Separately, though related, is the case of 'provides' type requirements, such as php-http/client-implementation. Obviously these should be excluded (as presumably a providing package is being required somewhere and will be picked up by Strauss separately), and this can be done manually in the strauss configuration for the root package, but skipping these automagically would be nice, though I am not sure how possible this is.

**Comment by BrianHenryIE** [comment]
Looks like the Packagist API will help address packages like [league/omnipay](https://repo.packagist.org/p2/league/omnipay.json).

Probably by doing ~ `if(!file_exists(...))`, which would also work with other non-standard package types, but I haven't looked at any yet.

I didn't notice that Strauss handles the `provides` key of packages. It's certainly not explicitly doing so, but maybe they're being pulled in via [Composer\Package\PackageInterface::getRequires()](https://github.com/composer/composer/blob/9a32bf9709960017f944753c68ab05c8de94add0/src/Composer/Package/PackageInterface.php#L240-L246). There are already default exclusions for psr* and ext-* which I'd expected would be expanded.

I'm busy for the next week but will take a look into this afterwards.

**Comment by BrianHenryIE** [comment]
OK, I've a branch with passing tests:
https://github.com/BrianHenryIE/strauss/blob/meta-packages/tests/Issues/StraussIssue22Test.php

It's reading the meta package from composer.lock (which I looked for before but thought it wasn't there!) and is ignoring the virtual package.

There some code duplication that needs to be tidied up:
https://github.com/BrianHenryIE/strauss/blob/78cf834882dbe9d06832ede9c0afd3d397ade53d/src/Console/Commands/Compose.php#L110-L235

And it needs a test with a package that requires a virtual package. And needs to be tested on Windows.

**Comment by BrianHenryIE** [comment]
I pushed some more changes to the branch. I don't foresee any more. Once I get a chance to write a few lines in the README I'll merge and push a new release to Packagist.
