### ISSUE TITLE
Namespace issues with static methods

### ISSUE THREAD

**Issue by adrianstaffen** [BrianHenryIE/strauss#23]
Hi, I'm coming from https://github.com/coenjacobs/mozart/issues/124 and wanted to give Strauss a go to fix my issues with mPDF & Mozart.

But Strauss is not replacing the old namespace with the new one when a static method is called. The are some cases in my codebase where also static methods get the updated namespace, but most of the times they do not.

I've created a simplified [gist](https://gist.github.com/adrianstaffen/836f87c6ea8973c5b5b034a629d25379) where I also attached the resulting file in which the non-static method gets the updated namespace and the static method does not. Is there something wrong with my composer.json or is Strauss not working correctly here? Thanks in advance!

**Comment by BrianHenryIE** [comment]
Fixed in [0.10.0](https://github.com/BrianHenryIE/strauss/releases/tag/0.10.0). Thank you.
