### ISSUE TITLE
Namespaces of static methods not replaced inside if statements and array declarations

### ISSUE THREAD

**Issue by adrianstaffen** [BrianHenryIE/strauss#25]
Hi again and thanks for fixing #23 @BrianHenryIE!

Now with Strauss 0.10.1 I could find more static method namespace issues.

Namespaces aren't replaced
- if the call is negated
- if the call inside an if condition is not the first condition
- if the call is inside an (associative) array declaration

For exact behavior I created a [gist](https://gist.github.com/adrianstaffen/e1df25cd62c17d3f1a4697db6c449034) with all kind of scenarios.

Thank you!

**Comment by BrianHenryIE** [comment]
Thanks. Great test cases. Keep 'em coming!
