### ISSUE TITLE
Configuration option include_modified_date doesn't work

### ISSUE THREAD

**Issue by adrianstaffen** [BrianHenryIE/strauss#35]
Hi,

when I add `"include_modified_date": false` to the `extra/strauss` object it doesn't take any effect, the date is still added to the header.

I also want to get rid of the author in the header, because I don't want git to include all files again after running strauss when actually the only change is the author in the header who ran strauss.

So a second option like `"include_author": false` would be much appreciated.

If both options are set to false the text would then be "Modified using Strauss.", which would not change if multiple authors run strauss on multiple dates.

Thank you!

**Comment by BrianHenryIE** [comment]
Hey. This is my bad practice: the `include_modified_date` option is working in `dev-master` but isn't in a Packagist `*` release yet.

I'll make a better effort not to merge to master unless ready to make a release.

**Comment by BrianHenryIE** [comment]
`include_author` option added in [v0.11.0 ](https://github.com/BrianHenryIE/strauss/releases/tag/0.11.0)and is [live on Packagist](https://packagist.org/packages/brianhenryie/strauss). Thank you.
