### ISSUE TITLE
Double namespacing issue when using nested namespace prefix

### ISSUE THREAD

**Issue by rickmacgillis** [BrianHenryIE/strauss#47]
Hi @BrianHenryIE. I'm having issues with Strauss adding the namespace prefix twice on my files. There doesn't appear to be any way to fix it. I've removed the custom prefix and let it use the default, and that default doesn't get added twice.

See: https://www.loom.com/share/dd52ab3e791840bdbf25bd45fcdeecf3

Here's a couple samples from the autoloader.

```php
'Dragon\Dependencies\Dragon\Dependencies\Ramsey\Uuid\FeatureSet' => $strauss . '/ramsey/uuid/src/FeatureSet.php',
'Dragon\Dependencies\Dragon\Dependencies\Doctrine\Common\EventArgs' => $strauss . '/doctrine/event-manager/lib/Doctrine/Common/EventArgs.php',
```

Here's the relevant chunk from my composer.json file.

```json
"extra": {
	    "strauss": {
			"target_directory": "strauss",
	        "namespace_prefix": "Dragon\\Dependencies\\",
	        "classmap_prefix": "DRAGON_",
	        "constant_prefix": "DRAGON_CONST_",
	        "packages": [
				"guzzlehttp/guzzle",
				"dragon-public/framework"
	        ],
	        "override_autoload": {
	        },
	        "exclude_from_copy": {
	            "packages": [
	            ],
	            "namespaces": [
	            ],
	            "file_patterns": [
	            ]
	        },
	        "exclude_from_prefix": {
	            "packages": [
	            ],
	            "namespaces": [
	            ],
	            "file_patterns": [
	                "/^psr.*$/"
	            ]
	        },
	        "namespace_replacement_patterns" : {
	        },
	        "delete_vendor_files": false
	    }
    }
```

Update:
It seems to only happen with nested namespace prefixes. Here's a sample after changing it to a single namespace. I'll use that, but it might be worth documenting/fixing.

```php
'DragonDependencies\Ramsey\Uuid\FeatureSet' => $strauss . '/ramsey/uuid/src/FeatureSet.php',
'DragonDependencies\Doctrine\Common\EventArgs' => $strauss . '/doctrine/event-manager/lib/Doctrine/Common/EventArgs.php',
```

**Comment by BrianHenryIE** [comment]
This is fixed now. The problem was the the namespace being replace was a substring of the replacing namespace. The prefixer/replacer class is handed a list of classnames and their replacements:
```
array (
  'Dragon\\Email' => 'Dragon\\Dependencies\\Dragon\\Email',
  'Dragon\\Form' => 'Dragon\\Dependencies\\Dragon\\Form',
  'Dragon' => 'Dragon\\Dependencies\\Dragon',
  'Dragon\\Hooking' => 'Dragon\\Dependencies\\Dragon\\Hooking',
)
```
The problem here is that as the array is iterated through, after the first two replacements are made, the `'Dragon' => 'Dragon\\Dependencies\\Dragon',` affects the updated string.

So the solution was to `asort()` so that that was done before any others.
