### ISSUE TITLE
Incorrect binary name when installed using composer

### ISSUE THREAD

**Issue by mikey242** [BrianHenryIE/strauss#51]
When installing this via composer the binary is called mozart and not strauss as mentioned in the documentation.

I get this:
`vendor/bin/mozart`

Instead of this:
`vendor/bin/strauss`

Have I missed something or is this a mistake?

**Comment by BrianHenryIE** [comment]
Yeah, that's weird. That's not how it is locally for me (in a WordPress plugin project). Maybe you've installed a very old version somehow? It was renamed a long time ago: https://github.com/BrianHenryIE/strauss/commit/9fe0eadc42691f52506e8fe730ba804e54136230

**Comment by mikey242** [comment]
Thanks for your reply @BrianHenryIE. I found the problem and it was my fault, apologies. My PHP platform setting in composer was set to PHP 7.2 which meant that when I ran the command to install strauss, it downloaded the latest compatible version which was 0.5.0 which was in fact before your fork.
