### ISSUE TITLE
Good idea to set `target_directory`to 'vendor'?

### ISSUE THREAD

**Issue by evrpress** [BrianHenryIE/strauss#52]
Thanks for the tool, like it so far!

I wonder if it's ok to set the output directory to 'vendor' to not have 'vendor_prefix' or simliar.

Currently I run `rm -rf vendor;mv vendor_prefix vendor` after the `strauss` command to only have one vendor folder which is also in my .gitignore.

Also I like to keep `brianhenryie/strauss` dependency in the 'require-dev' but that would bot work if running `composer update --no-dev` for the production build.  What's the expected approach here?

Thanks!

**Comment by BrianHenryIE** [comment]
Hey,

There is a branch started for setting the `target_directory` to `vendor` but I haven't written tests against it or really used it myself. It might be working fine, give it a try: https://github.com/BrianHenryIE/strauss/issues/34#issuecomment-922540372

And you can download and use the `.phar` file to avoid the need to install Strauss via Composer. There's a suggested issue to distribute through Phive, but I've yet to use that myself so it's not yet done: https://github.com/BrianHenryIE/strauss/issues/6 . The README describes downloading and using the Phar.
