### ISSUE TITLE
Still works?

### ISSUE THREAD

**Issue by UVLabs** [BrianHenryIE/strauss#61]
I'm running the library and it's only pulling and namespacing the `dealerdirect/phpcodesniffer-composer-installer` dependency which is actually a dev dependency..

Its totally ignoring a dependency not hosted on packagist and also one hosted there so it seems to just not be pulling my changes?

I also manually tried adding the packages to the "packages" array in the composer `extra` but it didn't have any effect.

My composer file:

```
{   
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/iconicwp/WordPress-Settings-Framework.git"
        }
    ],
    "scripts": {
        "prefix":  "vendor/bin/strauss"
    },
    "require-dev": {
        "dealerdirect/phpcodesniffer-composer-installer": "0.7.1",
        "wp-coding-standards/wpcs": "2.3",
        "suin/phpcs-psr4-sniff": "^3.0",
        "brianhenryie/strauss": "^0.13.0"
    },
    "autoload":{
        "psr-4": {
            "Namespace\\Subnamespace\\" : "includes/"
        },
        "classmap":[
            "vendor/iconicwp/wordpress-settings-framework/wp-settings-framework.php"
        ]
    },
    "require": {
        "iconicwp/wordpress-settings-framework": "dev-master",
        "freemius/wordpress-sdk": "^2.5"
    },
    "extra": {
        "strauss": {
            "target_directory": "vendor-prefixed",
            "packages": [
                "iconicwp/wordpress-settings-framework",
                "freemius/wordpress-sdk"
            ],
            "override_autoload": {
            },
            "exclude_from_copy": {
                "packages": [
                ],
                "namespaces": [
                ],
                "file_patterns": [
                ]
            },
            "exclude_from_prefix": {
                "packages": [
                ],
                "namespaces": [
                ],
                "file_patterns": [
                    "/^psr.*$/"
                ]
            },
            "namespace_replacement_patterns" : {
            },
            "delete_vendor_files": false
        }
    },
    "config": {
        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    }
    
}

```

When I run strauss this the `vendor-prefixed` library:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/10324144/217188671-9977f3a1-2c2d-4647-83f1-826165b3b350.png">

**Comment by UVLabs** [comment]
@BrianHenryIE I'd like to mention that things are working fine now just to be clear, strauss only copies packages that have at least 1 namespace right?

Because i noticed its skipping the freemius package all together, even when i explicity set "freemius/wordpress-sdk" inside the packages array in strauss, it doesn't do anything. I checked the freemius code and I can't identify any name spaces.

I also did a search for `namespace` inside the package and no results came up.

**Comment by BrianHenryIE** [comment]
More correctly it build the list of files to copy by looking at the `autoload` key. 

This code above is the fix:

```
"extra": {
    "strauss": {
      "override_autoload": {
        "freemius/wordpress-sdk": {
          "classmap": ["."]
        }
      },
```

Strauss is then prescribing that as Freemius's `composer.json`'s `autoload` value, `.` means current directory, which is relative to `composer.json`, i.e. the Freemius package root, and the `classmap` autoload type says to scan all PHP files and directories in the array for classes.
