### ISSUE TITLE
Error when "exclude-from-classmap"

### ISSUE THREAD

**Issue by nlemoine** [BrianHenryIE/strauss#7]
Hi, 

I'm trying to use your package in a plugin where I make use of some Symfony components.

When running `strauss`, I'm having the following error: 
`/full/path/to/project/vendor/symfony/process//Tests/" directory does not exist`

The "exclude-from-classmap" key doesn't seem to be handled in strauss. Could you have a look?

**Comment by BrianHenryIE** [comment]
Thanks. I've never encountered that in the wild myself, so hadn't had to address it yet.
