### ISSUE TITLE
Strauss Fail when a namespace is mapped to an array of paths

### ISSUE THREAD

**Issue by TheTBO** [BrianHenryIE/strauss#76]
when multiple directories are add for the same namespace as specified in [Composer documentaion](https://getcomposer.org/doc/04-schema.md#autoload):

```json
{
    "autoload": {
        "psr-4": { "Monolog\\": ["src/", "lib/"] }
    }
}

```
it results in the error: 
```
PHP Fatal error:  Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given in [REDACTED]/vendor/brianhenryie/strauss/src/Composer/Extra/StraussConfig.php:235
```

it seems like the problem is strauss always expect the configuration to be a string and try to trim() it.

**Comment by BrianHenryIE** [comment]
Weird, that should be fixed already #37 https://github.com/BrianHenryIE/strauss/commit/35d00430a66576adcac34cf7c50d7d9d13cca2b9. I'll take another look soon.

I think as a workaround this might work:
```
  "extra": {
        "strauss": {
            "override_autoload": {
                "monolog/monolog": {
                    "classmap": ["src/", "lib/"]
                }
            },
```

**Comment by TheTBO** [comment]
Thank you for the workaround.
Sorry but I'm a bit confused, the commit is about the FileEnumerator class which is not being used in [StraussConfig](https://github.com/BrianHenryIE/strauss/blob/35d00430a66576adcac34cf7c50d7d9d13cca2b9/src/Composer/Extra/StraussConfig.php#L229) constructor where the error happen  
```php
            // Check each autoloader.
            foreach ($composer->getPackage()->getAutoload() as $autoload) {
                // To see if one of its paths.
                foreach ($autoload as $path) {
                    // Matches the target directory.
                    if (trim($path, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR === $this->getTargetDirectory()) {
                        $this->classmapOutput = false;
                        break 2;
                    }
                }
            }
```
Furthermore, the test case doesn't seem to include PSR-0/PSR-4 config at all.

**Comment by BrianHenryIE** [comment]
Can you give me an actual broken composer.json. I've tried writing tests with the example you gave me and they're passing.

**Comment by TheTBO** [comment]
Sure, here [composer.json](https://github.com/BrianHenryIE/strauss/files/13197956/composer.json)
it's a modified version from [fakerpress](https://github.com/bordoni/fakerpress/blob/main/composer.json)

**Comment by BrianHenryIE** [comment]
This should be fixed in master now. See: https://github.com/BrianHenryIE/strauss/commit/b32fe49b6563802ffb1152f34069071eec950531

**Comment by TheTBO** [comment]
Great, It works flawlessly now. 
Thank you very much.
