### ISSUE TITLE
Remove wrong information about zero configuration

### ISSUE THREAD

**Issue by sovetski** [BrianHenryIE/strauss#85]
Hi,

On the documentation we can see "Strauss potentially requires zero configuration", but when we just install the library and run the code, it says: 

```
[info] Loading config...
[error] Prefix not set. Please set `namespace_prefix`, `classmap_prefix` in composer.json/extra/strauss.
```

**Comment by BrianHenryIE** [comment]
Yes, _potentially_, depending on your existing composer.json. See: 

https://github.com/BrianHenryIE/strauss/blob/6cb008b38c05ce5cd316b5cdf17d0b43621ef39a/tests/Unit/Composer/Extra/StraussConfigTest.php#L177-L206
