### ISSUE TITLE
Strauss 0.16.0 output wrong version number

### ISSUE THREAD

**Issue by ravinderk** [BrianHenryIE/strauss#90]
## Details
Latest version still pointing to older version.

https://github.com/BrianHenryIE/strauss/blob/6518699c8f96951a950f542a263d97a5f3fffb34/bin/strauss#L29

**Comment by BrianHenryIE** [comment]
This is fixed for the phar but not when you install through Packagist.

I'm not sure how to do it except manually. I think if I were to be disciplined and keep a changelog, then there could be a GitHub Action that would calculate the next version number and make the change before I create the release.

**Comment by BrianHenryIE** [comment]
I've added a workflow to update the version number from CHANGELOG.md

https://github.com/BrianHenryIE/strauss/blob/master/.github/workflows/updateversionfromchangelog.yml

https://github.com/BrianHenryIE/strauss/commit/82f2dca5221086fe7d58343ae70ce5f23499a137

**Comment by ravinderk** [comment]
@BrianHenryIE Thank you for fixing this.
